name: CI for myLittleShop
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for Docker
        run: |
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> .env
          echo "MONGO_EXP_PASSWORD=${{ secrets.MONGO_EXP_PASS }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env

      - name: Start Docker Containers
        run: |
          docker compose up -d

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/${{ secrets.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SPRING_DATA_MONGODB_URI: "mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongodb:27017/cart?authSource=admin"
          SPRING_MAIL_HOST: ${{ secrets.MAIL_HOST }}
          SPRING_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          chmod +x mvnw
          ./mvnw clean package -e

      - name: Verify OpenAPI Documentation
        run: |
          if cmp -s docs/openapi.json target/openapi-temp/openapi.json; then
              echo "OpenAPI documentation is up to date."
          else
              echo "ERROR: OpenAPI documentation is outdated!"
              exit 1
          fi